// Date: 9/16/2014 8:57:48 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package com.pokemine.client.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelPokemonTest extends ModelBase {
	// fields
	ModelRenderer head;
	ModelRenderer body;
	ModelRenderer leg1;
	ModelRenderer leg2;
	ModelRenderer leg3;
	ModelRenderer leg4;
	ModelRenderer udders;

	public ModelPokemonTest() {
		this.textureWidth = 64;
		this.textureHeight = 32;

		this.head = new ModelRenderer(this, 0, 0);
		this.head.addBox(-4F, -4F, -6F, 8, 8, 6);
		this.head.setRotationPoint(0F, 4F, -8F);
		this.head.setTextureSize(64, 32);
		this.head.mirror = true;
		setRotation(this.head, 0F, 0F, 0F);
		this.body = new ModelRenderer(this, 18, 4);
		this.body.addBox(-6F, -10F, -7F, 12, 18, 10);
		this.body.setRotationPoint(0F, 5F, 2F);
		this.body.setTextureSize(64, 32);
		this.body.mirror = true;
		setRotation(this.body, 1.570796F, 0F, 0F);
		this.leg1 = new ModelRenderer(this, 0, 16);
		this.leg1.addBox(-3F, 0F, -2F, 4, 6, 4);
		this.leg1.setRotationPoint(-3F, 12F, 7F);
		this.leg1.setTextureSize(64, 32);
		this.leg1.mirror = true;
		setRotation(this.leg1, 0F, 0F, 0F);
		this.leg2 = new ModelRenderer(this, 0, 16);
		this.leg2.addBox(-1F, 0F, -2F, 4, 6, 4);
		this.leg2.setRotationPoint(3F, 12F, 7F);
		this.leg2.setTextureSize(64, 32);
		this.leg2.mirror = true;
		setRotation(this.leg2, 0F, 0F, 0F);
		this.leg3 = new ModelRenderer(this, 0, 16);
		this.leg3.addBox(-3F, 0F, -3F, 4, 6, 4);
		this.leg3.setRotationPoint(-3F, 12F, -5F);
		this.leg3.setTextureSize(64, 32);
		this.leg3.mirror = true;
		setRotation(this.leg3, 0F, 0F, 0F);
		this.leg4 = new ModelRenderer(this, 0, 16);
		this.leg4.addBox(-1F, 0F, -3F, 4, 6, 4);
		this.leg4.setRotationPoint(3F, 12F, -5F);
		this.leg4.setTextureSize(64, 32);
		this.leg4.mirror = true;
		setRotation(this.leg4, 0F, 0F, 0F);
		this.udders = new ModelRenderer(this, 52, 0);
		this.udders.addBox(-2F, -3F, 0F, 4, 6, 2);
		this.udders.setRotationPoint(0F, 14F, 6F);
		this.udders.setTextureSize(64, 32);
		this.udders.mirror = true;
		setRotation(this.udders, 1.570796F, 0F, 0F);
	}

	public void render(Entity entity, float f, float f1, float f2, float f3,
			float f4, float f5) {
		super.render(entity, f, f1, f2, f3, f4, f5);
		setRotationAngles(entity, f, f1, f2, f3, f4, f5);
		this.head.render(f5);
		this.body.render(f5);
		this.leg1.render(f5);
		this.leg2.render(f5);
		this.leg3.render(f5);
		this.leg4.render(f5);
		this.udders.render(f5);
	}

	private void setRotation(ModelRenderer model, float x, float y, float z) {
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}

	public void setRotationAngles(Entity entity, float f, float f1, float f2, float f3,
			float f4, float f5) {
		super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
	}

}
